from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(496, 589)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.IDNumber = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.IDNumber.setGeometry(QtCore.QRect(10, 50, 471, 31))
        self.IDNumber.setPlaceholderText("")
        self.IDNumber.setObjectName("IDNumber")
        self.HeaderText = QtWidgets.QLabel(parent=self.centralwidget)
        self.HeaderText.setGeometry(QtCore.QRect(10, 0, 471, 31))
        self.HeaderText.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.HeaderText.setObjectName("HeaderText")
        self.VoterIdText = QtWidgets.QLabel(parent=self.centralwidget)
        self.VoterIdText.setGeometry(QtCore.QRect(10, 20, 471, 31))
        self.VoterIdText.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.VoterIdText.setObjectName("VoterIdText")
        self.CanidateText = QtWidgets.QLabel(parent=self.centralwidget)
        self.CanidateText.setGeometry(QtCore.QRect(10, 90, 471, 31))
        self.CanidateText.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.CanidateText.setObjectName("CanidateText")
        self.SubmiButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.SubmiButton.setGeometry(QtCore.QRect(20, 410, 451, 32))
        self.SubmiButton.setObjectName("SubmiButton")
        self.ResultsText = QtWidgets.QLabel(parent=self.centralwidget)
        self.ResultsText.setGeometry(QtCore.QRect(10, 460, 151, 31))
        self.ResultsText.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ResultsText.setObjectName("ResultsText")
        self.ResultsLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.ResultsLabel.setGeometry(QtCore.QRect(210, 450, 251, 51))
        self.ResultsLabel.setObjectName("ResultsLabel")
        self.layoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 130, 471, 261))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.BiancaButton = QtWidgets.QPushButton(parent=self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BiancaButton.sizePolicy().hasHeightForWidth())
        self.BiancaButton.setSizePolicy(sizePolicy)
        self.BiancaButton.setObjectName("BiancaButton")
        self.horizontalLayout.addWidget(self.BiancaButton)
        self.EdwardButton = QtWidgets.QPushButton(parent=self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EdwardButton.sizePolicy().hasHeightForWidth())
        self.EdwardButton.setSizePolicy(sizePolicy)
        self.EdwardButton.setObjectName("EdwardButton")
        self.horizontalLayout.addWidget(self.EdwardButton)
        self.FeliciaButton = QtWidgets.QPushButton(parent=self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FeliciaButton.sizePolicy().hasHeightForWidth())
        self.FeliciaButton.setSizePolicy(sizePolicy)
        self.FeliciaButton.setObjectName("FeliciaButton")
        self.horizontalLayout.addWidget(self.FeliciaButton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 496, 37))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.HeaderText.setText(_translate("MainWindow", "VOTING MENU"))
        self.VoterIdText.setText(_translate("MainWindow", "Enter Voter ID:"))
        self.CanidateText.setText(_translate("MainWindow", "Canidates (Pick One)"))
        self.SubmiButton.setText(_translate("MainWindow", "Submit"))
        self.ResultsText.setText(_translate("MainWindow", "Results"))
        self.ResultsLabel.setText(_translate("MainWindow", "TextLabel"))
        self.BiancaButton.setText(_translate("MainWindow", "Bianca"))
        self.EdwardButton.setText(_translate("MainWindow", "Edward"))
        self.FeliciaButton.setText(_translate("MainWindow", "Felicia"))
